### ISSUE TITLE
future development checklist

### ISSUE THREAD

**Issue by jlnrrg** [doersino/nyum#1]
I just found your piece of art and I am head over heals.
Even though you write to have no real ambition to continue the project, 
I still like to provide a checklist of interesting features so me or other people can add wish and contribute ourselfes.

## appearance
- [ ] dark mode
- [ ] include the picture in the overview
- [ ] overview page -> a better limitation view for categories (useful for a lot of recipes)
- [ ] overview page -> change title + text to a centered with boxconstraints
- [ ] recipe page -> add an highlight point, which expresses visually where to take extra caution
- [ ] do not create a scrollable list for instructions (I noticed this by using 8 steps, and the last one was empty)

## functionality
- [ ] powerful search
  - [ ] search by label
  - [ ] navigate with arrow keys
- [ ] a language extension (e.g. strawberrysmoothie_en.md), for multilingual support
- [ ] on generation generate a "cookbook" pdf with pandoc that can be downloaded directly (+ single pages based on recipe)
- [ ] overview page -> extend `<a></a>` over whole ListItem and not just the title

## content
- [ ] content, which won't be publicly available
- [ ] a general overview of all required ingrediences (not autogenerated), <br> which has no instruction number (like [chowdown](https://chowdown.io/recipes/banana-bread.html)
- [ ] support of deep `_recipes` folders which translate to categories
- [x] change of ✓ in markdown files to simple "x"
- [ ] Adding title attributes for the icons on the index page. Minor, but relevant for accessibility.

## generation
- [ ] github action to auto generate on new recipes added (possibly using [this](https://github.com/pandoc/pandoc-action-example))
- [ ] image tag in header, which downloads the image on generation <br> and adds a visible source in the html output (bc copyright)
- [ ] change to hugo (it is no intend to bash 😅, and more a note for me to consider in the future)
- [ ] allowing the [hRecipe](https://github.com/dpapathanasiou/recipebook) json as input and providing a parser for this site's recipes

## other
- [ ] spreading the word, by contributing to different awesome lists like [this](https://github.com/bbbenji/awesome-recipes) and [that](https://github.com/jzarca01/awesome-food)
- [ ] Simplify the code in build.sh dealing with uncategorized recipes.
- [ ] add a list of all supported md header settings in the README.md

Feel free to add anything or even edit my post for convenience sake.

**Comment by doersino** [comment]
Hiya! First off, *thank you* for taking the time to compile such an exhaustive list – it always makes me really happy when something I publish gets folks excited!

There are **some points that I'd indeed like to tackle** (likely this coming weekend):

* [ ] Navigating the search results using the the <kbd>↑</kbd>/<kbd>↓</kbd> and <kbd>enter</kbd> keys.
* [ ] At least in search results, extending `<a></a>` over the whole list item and not just the title, along with a slightly different background color on hover. (Inside the main portion of the index page, the user could have added their own links as part of recipe descriptions. Wrapping the link to the recipe around the whole list item would render such links inoperable.)
* [ ] Optionally displaying each recipe's image on in the index page, this will be a setting in `config.yaml` and disabled by default.
* [ ] *Possibly* dark mode. Since SVGs embedded via `<img>` tags [aren't](https://stackoverflow.com/questions/8102528/how-do-you-access-the-contents-of-an-svg-file-in-an-img-element) part of the DOM, I'll probably have to inline the icons for this, which is kind of annoying.

In addition, some things that **weren't on your list**:

* [ ] Simplify the code in `build.sh` dealing with uncategorized recipes.
* [ ] Adding title attributes for the icons on the index page. Minor, but relevant for accessibility.

The following is **already possible**:

* Changing of "✓" in Markdown files to a simple "x" – in fact, any non-empty and (if you've got a [fairly recent](https://github.com/jgm/pandoc/issues/6650) version of Pandoc) non-falsey value will have the same effect.

And I'm sorry to disappoint you: Most of your other suggestions are, **as far as I'm concerned, outside the scope of this project**:

* As I've written in the readme, I prefer the relevant-ingredients-next-to-instructions structure over the more common all-ingredients-first-then-a-block-of-instructions approach you're suggesting. That's part of the reason why I've built *this* tool instead of simply using an already-existing one. Maintaining both "modes" in parallel would be more work and, more importantly, it would reduce what I'd call the "[dogfooding](https://en.wikipedia.org/wiki/Eating_your_own_dog_food) coverage".
* Any integrations with (or importing of, or exporting to) alternative recipe formats aren't something I'd personally utilize, so they're out for the same reasons.
* A GitHub action for deployment is something any user of this tool could build for their own instance if desired.
* I feel like built-in multilingual support (with little flag icons on recipe pages, I support) isn't super relevant in the "personal recipe collection" use case this tool is built for.
* Generating a "cookbook" PDF with Pandoc that can be downloaded directly is a cool idea, but then I'd have to deal with LaTeX for styling – and my falling out of love with LaTeX was part of the impetus for building this tool. 😉

All of the above **shouldn't keep anyone from forking nyum and making it their own**, though – it's deliberately simple *and* licensed under the [MIT License](https://github.com/doersino/nyum/blob/main/LICENSE), so there's very few limits on what you can do. You could take the design and turn it into a Hugo theme, for instance.

Finally, I'm afraid I don't quite understand what you mean by "overview page -> a better limitation view for categories (useful for a lot of recipes)". It sounds intriguing, could you elaborate?

**Comment by doersino** [comment]
Closing since I've now addressed all the points laid out in my comment (and more).

If any of your remaining suggestions is really important to you, feel free to file them as separate issues!

**Comment by jlnrrg** [comment]
Thanks for your efford.
This was only a collection as I noticed a bunch of stuff in the beginning. So I totally agree with future single issues 😄.
